project:
  type: website

website:
  title: "yhkee0404.github.io"
  navbar:
    left:
      - text: Algorithms
        href: algorithms.qmd#category=featured
      - text: Bible
        href: bible.qmd#category=featured
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yhkee0404/yhkee0404.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/yunho-kee-2a4878256/
      - icon: twitter-x
        href: https://twitter.com/yhkee0404
      - icon: chat-left-quote-fill
        href: https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fyhkee0404.github.io%2F%2A
  comments:
    hypothesis:
      enableExperimentalNewNoteButton: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    highlight-style: github



