project:
  type: website
  resources:
    - "_js/"

website:
  title: "Source Thoughts in a Monorepo"
  description: "a personal cloud diary of Yunho Kee, a software engineer"
  page-footer: "Copyright 2023-2025, Yunho Kee"
  site-url: https://yhkee0404.github.io
  image: haezoom-everland-jyh-lunapic.jpg
  open-graph:
    locale: ko_KR
  google-analytics: G-KH3KTM2DG3
  navbar:
    title: "Source Thoughts in a Monorepo"
    left:
      - text: Web
        href: web.qmd#category=featured
      - text: Database
        href: database.qmd#category=featured
      - text: Data Science
        href: data-science.qmd#category=featured
      - text: Algorithms
        href: algorithms.qmd#category=featured
      - text: Troubleshoot
        href: troubleshoot.qmd#category=featured
    right:
      - text: CV
        href: cv/ko/index.qmd
      - icon: github
        href: https://github.com/yhkee0404/yhkee0404.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/yunho-kee-2a4878256/
      - icon: twitter-x
        href: https://twitter.com/yhkee0404
      - icon: chat-left-quote-fill
        href: https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fyhkee0404.github.io%2F%2A
      - icon: rss
        href: index-featured.xml
  comments:
    hypothesis:
      enableExperimentalNewNoteButton: true
  back-to-top-navigation: true
format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: github
    toc: true
    # toc-location: right-body
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true

