project:
  type: website
  resources:
    - "_js/"

website:
  title: "Source Thoughts in a Monorepo"
  description: "a personal cloud diary of Yunho Kee, a software engineer"
  page-footer: "Copyright 2023-2025, Yunho Kee"
  site-url: https://yhkee0404.github.io
  image: _images/portrait/haezoom-everland-jyh-lunapic.jpg
  image-alt: "A photo of him looking at butterflies"
  open-graph:
    locale: ko_KR
  google-analytics: G-KH3KTM2DG3
  navbar:
    title: "Source Thoughts in a Monorepo"
    left:
      - text: Web
        href: listings/web.qmd
      - text: Database
        href: listings/database.qmd
      - text: Data Science
        href: listings/data-science.qmd
      - text: Algorithms
        href: listings/algorithms.qmd
      - text: Troubleshoot
        href: listings/troubleshoot.qmd
    right:
      - text: CV
        href: cv/ko/index.qmd
      - icon: github
        href: https://github.com/yhkee0404/yhkee0404.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/yunho-kee-2a4878256/
      - icon: twitter-x
        href: https://twitter.com/yhkee0404
      - icon: chat-left-quote-fill
        href: https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fyhkee0404.github.io%2F%2A
      - icon: rss
        href: index.xml
  comments:
    hypothesis:
      enableExperimentalNewNoteButton: true
  back-to-top-navigation: true
  draft-mode: visible
format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: github
    toc: true
    # toc-location: right-body
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true

resource-path:
  - ../../../_bibliographies/book/
  - ../../../_bibliographies/online/
  - ../../../../_bibliographies/book/
  - ../../../../_bibliographies/online/