---
title: "Philemon"
author: "Yunho Kee"
date: "2024-02-14"
date-modified: "2024-03-06"
categories:
  - bible
  - Philemon
  - Paul
  - Timothy
  - Apphia
  - Archippus
  - Onesimus
  - Epaphras
  - Mark
  - Aristarchus
  - Demas
  - Luke
---

Greetings from  
This letter is from  
I am writing to  
Paul's Final Greetings  
send you his greetings  
So do  

May give you grace and peace  
May the grace of be with your spirit  

One more thing—  
please prepare a guest room for me  
I am hoping  
God will answer your prayers  
let me return to you soon  

send back to  
with him comes my own heart  
for a little while  
have back forever  

keep here with me  
while here  
while I am  
help on your behalf  

That is why  

has been in the past  
wanted and he would have helped  
It seems you lost so that you could  

I  
with my own hand  
owe me your very soul  
And I won't mention  

I am confident as  
and even more!  

a prisoner for preaching  
a prisoner for the sake of  
in prison  
in these chains for  

an old man  

preaching the Good News  

the Good News about  

Christ Jesus  
the Lord Jesus Christ  
the Lord Jesus  
Christ  
for the Lord's sake  
encouragement in Christ  

God our Father  
my God  

God's people  

누가 하나님의 사람인가  

my brother  
my child  
both of us  
to you  
especially to me  
consider me your partner  
welcome as you would  
Yes  

wrong in any way  
owe anything  

charge to  
repay  

our brother  
our beloved co-worker  
our sister  
our fellow soldier  
the church  
my fellow prisoner  
my co-workers  

집에서 모이는 교회도 있다.  

our love  
become his father in the faith  
a beloved brother  
mean much more as  
show kindness to  
a brother in the Lord  

of much use  
very useful  
no longer like a slave  
more than a slave  
a man  

Paul's Thanksgiving  
always thank when I pray  
love for all of  

사람이 하나님을 믿고 하나님의 사람들 모두를 사랑해서 하나님께 감사하다.  

Pray  
pray for  
pray that you will  
put into action the generosity  

understand and experience  
all the good things we have in  

사람을 위해 기도한다.  

믿는 사람은 이해하고 경험하면서 너그러워진다.  
행동까지 너그러워지게 기도한다.  

give me much joy and comfort  
your kindness  
often refresh the hearts of  

친절은 종종 사람들의 마음을 회복시킨다.  
사람들이 마음을 회복할수록 기분이 좋다.  

Appeal for  
a request from  
I am boldly asking  
I appeal to you to show  
ask a favor of  
do a favor for  
please  
Give me this encouragement in  

could demand  
demand in the name  
it is the right thing  
prefer simply to ask  
Consider this as a request  
an old man  

anything without your consent  
help because you were willing  
not because you were forced  

# References  

1. New Living Translation. (2015). Tyndale. <https://www.tyndale.com/nlt/search>  
