kind: Kustomization

namePrefix: example-my-fastapi-project-

resources:
  - ../../../../../../_kubernetes/example/services/api/staging

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: app-env
    behavior: merge
    literals:
      - SOMETHING=specific-for-staging
