---
title: "Yunho Kee"
# Keep date from being printed in MS Word
date-modified: 2025-05-08
blog: "https://yhkee0404.github.io/cv/en/"
format-links:
  - text: Korean
    href: ../ko/
    icon: translate
    rel: alternate
    # hreflang: ko-KR
  - text: PDF Viewer
    href: https://github.com/yhkee0404/yhkee0404.github.io/blob/gh-pages/cv/en/yhkee0404.pdf
    icon: file-pdf-fill
    rel: alternate
    target: _blank
  - text: PDF
    href: yhkee0404.pdf
    icon: file-pdf
    rel: alternate
    target: _blank
  - docx
---

{{< include ../_links.qmd >}}

::::::{.content-visible when-format="html"}

:::::{.quarto-about-jolla}

::::{.about-entity}

:::{.about-links}

```{=html}
<a href="../ko/" class="about-link" rel="alternate" hreflang="ko-KR">
  <i class="bi bi-translate"></i><span class="about-link-text">Switch to Korean</span>
</a>

<a href="https://github.com/yhkee0404/yhkee0404.github.io/blob/gh-pages/cv/en/yhkee0404.pdf" class="about-link" rel="alternate" target="_blank">
  <i class="bi bi-file-pdf-fill"></i><span class="about-link-text">View PDF</span>
</a>

<a href="yhkee0404.pdf" class="about-link" rel="alternate" target="_blank">
  <i class="bi bi-file-pdf"></i><span class="about-link-text">Download PDF</span>
</a>

<a href="yhkee0404.docx" class="about-link" rel="alternate" target="_blank">
  <i class="bi bi-file-word"></i><span class="about-link-text">Download MS Word</span>
</a>

<a href="https://github.com/yhkee0404/yhkee0404.github.io/blob/main/cv/en/index.qmd" class="about-link" rel="alternate" target="_blank">
  <i class="bi bi-github"></i><span class="about-link-text">View Source</span>
</a>
```

:::

::::

:::::

::::::

# OBJECTIVE

:::{custom-style="Custom Justified" .column-page-inset}

To design [feasible][ticketmaster] systems and fill in the gaps in reusable software by leveraging the principles of computer science

:::

# SKILLS

:::{custom-style="Custom Justified" .column-page-inset style="text-align-last: center;"}

Java | Spring Framework | Python | Django REST Framework | FastAPI | JavaScript | Apache Airflow | Celery | Amazon DynamoDB | PostgreSQL | Oracle | GitHub Action | Maven | Terraform Cloud | AWS IAM | SSH Tunneling 

:::

# WORK EXPERIENCE

:::::{custom-style="Custom Bullet"}

:::{.column-screen-inset}

||||
-|:-:|-:|-|-
**Backend Developer** | **[Haezoom][haezoom]** | Seoul, South Korea | &numsp;1 yr&ensp; &numsp;9 mos | 12/2022 - 08/2024 

: {tbl-colwidths="[24,24,20,14,18]"}

:::

### Solar Power Forecasting System Enhancement (50k+ daily transactions)

Fixed the algorithm with leakage, boundary errors, invalid cache, and timezone bugs ([**open source contribution**][pvlib linkedin])

Fulfilled **24x more frequent** requests, reducing processing time from 3 hours to 2 minutes (**90x faster**) through chunking, file compression, tensor transposition, and preprocessing (AWS Fargate, NumPy, netCDF4, SciPy)

Optimized coordinate transformation by reverse engineering (**47 s &rarr; 14 &micro;s**, **float32 &rarr; float64**, **99.55% &rarr; 100%**)

Polled asynchronous inputs using non-blocking read-through caching and two-pointer techniques (Apache Airflow)

Customized **serializers** to respond in the requested **timezone** and **autofill** periods (Django REST Framework)

Integrated third-party APIs for consistent geocoding, reverse geocoding, and address search (FastAPI)

### Settlement System Development (10k+ daily inserts)

Utilized [primitive **floating-point numbers**][decimal-round-down] instead of **decimal** objects, testing accuracy against [online judge data][1.5e-1]

Modeled formulas as directed acylic graphs (**DAGs**) loaded by reflection and evaluated asynchronously (Celery)

Stored results as **segment trees** with **soft delete**, **partial indexes**, and **covering indexes** (PostgreSQL)

Customized **filters** to set the default **timezone** and **autocomplete** periods from dates (Django REST Framework)

### Cloud Security System Development (RBAC, ABAC, Terraform Cloud, AWS IAM)

Managed just-in-time access using **roles**, break-glass access via **tags**, and network infrastructure as code (**IaC**)

::::{.content-visible when-format="html"}
:::{.hidden}
## dummy
:::
::::

:::{.column-screen-inset}

||||
-|:-:|-:|-|-
**DevOps Engineer** | **[MidasIn][jobda]** | Pangyo, South Korea | &numsp;&numsp; &ensp;&ensp;&ensp; &numsp;5 mos | 05/2022 - 09/2022 

: {tbl-colwidths="[24,24,20,14,18]"}

:::

Developed a **cross-account** AWS user management system with **observability** (Spring Boot, Fluent Bit, Datadog)

::::{.content-visible when-format="html"}
:::{.hidden}
## dummy
:::
::::

:::{.column-screen-inset}

||||
-|:-:|-:|-|-
**Software Developer** | **Republic of Korea Navy** | South Korea | &numsp;1 yr&ensp; &numsp;8 mos | 06/2020 - 02/2022 

: {tbl-colwidths="[24,24,20,14,18]"}

:::

Developed an **internet-based** [grievance service][ndts] and **intranet** services for educational assessment ([**exceptional award**](https://yhkee0404.github.io/_images/certificates/navy.jpg)), mental health assessment, and attendance management, fixing [missing rows][escape-xml10] (Spring Framework, Oracle)

:::::

# PROJECTS

::::{custom-style="Custom Bullet"}

:::{.column-screen-inset}

||
-|-|-
**[LeetCode Daily Google Sheets Apps Script][leetcode-daily-google-sheets-apps-script]** (JavaScript, GraphQL) | &numsp;&numsp; &ensp;&ensp;&ensp; &numsp;1 mo&ensp; | 01/2025 - 02/2025 

: {tbl-colwidths="[68,14,18]"}

:::

Replaced individual uploads with periodic [**crawling**][leetcode-daily-crawling], and an optional Chrome extension with a **bookmarklet** script

:::{.column-screen-inset}

||
-|-|-
**[Woowacourse Java Format][woowacourse-java-format]** (Java, Gradle, Maven, GitHub Actions)  | &numsp;&numsp; &ensp;&ensp;&ensp; &numsp;2 mos | 10/2024 - 11/2024 

: {tbl-colwidths="[68,14,18]"}

:::

Deployed IDE plugins (IntelliJ, Eclipse), **cross-platform** binaries (macOS, Linux, Windows), and to [Maven Central][central-portal]

:::{.column-screen-inset}

||
-|-|-
**[WICWIU][wicwiu]** (C++, CUDA, cuDNN, CNN, Batch Normalization, ReLU, Sigmoid) | &numsp;&numsp; &ensp;&ensp;&ensp; 10 mos | 07/2017 - 05/2018 

: {tbl-colwidths="[68,14,18]"}

:::

Released the **first** [open-source][open-source] deep learning framework among Korean universities ([**outstanding paper award**][outstanding paper award])

::::

# CONTRIBUTIONS

:::{custom-style="Custom Justified" .column-page-inset}

[Quarto][quarto 2] (PowerShell), [Posit][posit] ([RStudio Inc][rstudio]) | [pvlib python][pvlib linkedin], [Sandia (SNL)][sandia] | [Static JIRA issue export][jira-export] (PHP), [Netresearch][netresearch] | [Python Polylith Example][python-polylith-example] (Serverless Framework) | [Course: GitHub Pages][github-pages-template], 61.8k ([42k][github skills]+[19.8k][github learning lab]) repositories (Jekyll)

:::

# EDUCATION

:::{.column-screen-inset}

```{=html}
<table>
  <colgroup>
    <col style="width: 48%">
    <col style="width: 20%">
    <col style="width: 14%">
    <col style="width: 18%">
  </colgroup>
  <tbody>
    <tr>
      <td colspan="4">
        <span data-qmd="**B.S. in Computer Science and Engineering** ([Seoul Accord](https://www.abeek.or.kr/abeek/seoul/) recognized program), GPA 3.95/4.5 (**Cum Laude**)"></span>
      </td>
    </tr>
    <tr>
      <td style="text-align: right;"><strong>Handong Global University</strong></td>
      <td style="text-align: right;">Pohang, South Korea</td>
      <td>&numsp;5 yrs</td>
      <td>03/2015 - 02/2020</td>
    </tr>
  </tbody>
</table>
```

:::

:::{custom-style="Custom Bullet"}

2019 ACM-ICPC Seoul Regional [Finalist][seoul regional]

**Teaching Assistant:** ICT Problem Solving (Spring 2019), Computer Architecture and Organization (Fall 2018), Algorithms Analysis (Spring 2018), C Programming Lab (Fall 2017), C Programming (CSEE) (Summer 2017)

:::

# CERTIFICATIONS

:::{.column-screen-inset}

```{=html}
<table>
  <colgroup>
    <col style="width: 48%">
    <col style="width: 20%">
    <col style="width: 14%">
    <col style="width: 18%">
  </colgroup>
  <tbody>
    <tr>
      <td colspan="4"><strong>Engineer Information Processing</strong></td>
    </tr>
    <tr>
      <td style="text-align: right;"><strong>National Technical Qualification</strong></td>
      <td style="text-align: right;">South Korea</td>
      <td style="text-align: center;">-</td>
      <td>08/2021</td>
    </tr>
  </tbody>
</table>
```

:::