---
title: "오픈소스 이력서 엔지니어링"
author: "Yunho Kee"
date: "2025-05-10"
categories:
  - "database"
  - "cv"
  - "resume"
  - "monorepo"
  - "cross-platform"
  - "inverted index"
  - "open-source"
aliases:
  - /posts/database/cv-or-resume/draft
bibliography:
  - king_dropbox_sharelist.bib
  - king_ticketmaster_search.bib
draft: true
search: false
comments: false
adsense:
  enable-ads: false
---

# Problems

컴퓨터로 작성한 문서를 인쇄할 때 불편했던 적이 있나요?

1. 네이티브 기능 변경 미지원

  Notion이나 Confluence 문서를 작성하거나 웹페이지의 양식을 작성하면 편집 화면과 다르게 인쇄되거나 변환되는데도 주어진 양식을 변경하기 어려워요.

2. 크로스 플랫폼 미지원

  Figma나 LaTeX으로 PDF를 만들면 일부 회사에서 MS Word 문서를 요구하는 경우에 다르게 변환돼서 따로 만들어야 해요. MS Word를 열고 PDF의 캡처 이미지를 넣는 것으로 충분할까요?

3. 비교 어려움

  PDF나 MS Word 문서 내용을 확인하려면 웹 브라우저 또는 전용 프로그램으로 열어야 하고, 열고 나서도 잘못 고쳤거나 못 고친 부분이 없는지 확인하기 어려워요.

4. 네이티브 작성 어려움

  LaTeX이나 웹페이지의 소스코드는 Git 같은 버전 관리 시스템으로 비교하기 편한 텍스트이지만 작성 자체가 어려워요.

# Solution

Pandoc을 확장한 Quarto를 사용하면 Markdown을 바탕으로 일부 네이티브 기능을 지원하는 소스코드를 포함한 문서를 작성하고 다양한 파일로 변환할 수 있어요.

1. 네이티브 기능 변경 지원

  MS Word와 웹페이지로 변환한 결과가 예상과 다르면 주어진 MS Word 양식이나 CSS 파일을 변경할 수 있어요.

2. 크로스 플랫폼 지원

  MS Word를 PDF로 자동 변환하거나, 동시에 웹페이지를 배포할 수 있어요.

3. 비교 쉬움

  텍스트를 작성한 시점에 따라 GitHub UI로 비교하기 쉽고, 같은 내용을 분산하지 않는 모노레포로 관리하기 때문에 서로 다른 파일을 비교할 필요가 없어요.

4. 네이티브 작성 쉬움

  Notion이나 Confluence만큼 작성하기 쉬운 Markdown를 작성하고 일부 네이티브 기능을 지원하는 소스코드를 포함해요.

# Open Source CV or Resume

이렇게 작성한 제 이력서는 사진과 같아요.
소스코드를 [여기](https://github.com/yhkee0404/yhkee0404.github.io/blob/main/cv/ko/index.qmd)에서 오픈 소스로 공개할 테니 더 잘 만드실 수 있는 분은 공유해 주세요.

[Fork](https://github.com/yhkee0404/yhkee0404.github.io/fork)하시고,
[GitHub Pages](https://quarto.org/docs/publishing/github-pages.html#source-branch)를 설정해 보세요.

또는 Docker Compose를 [설치](https://docs.docker.com/compose/install/)하시고 Terminal에서 다음 명령을 실행 후 `https://localhost:8888/`에 접속해 보세요:

```sh
git clone https://github.com/yhkee0404/yhkee0404.github.io
docker compose up -d --force-recreate quarto-preview
```

어려운 점은 무엇이든 알려 주시면 도와드릴게요.
reference.docx를 만들고 스타일을 적용하는 방법은 [여기](https://quarto.org/docs/output-formats/ms-word-templates.html)를 참고하시면 됩니다.
제가 설정한 내용은 문서 내에 모두 정리해 두었습니다.

# Engineering

기존의 문제는 전통적인 관계형 데이터베이스의 이상 현상(Anomaly)으로도 설명할 수 있어요.

:::{.column-page-inset}

|       파일명      |      사진      | 다운로드 버튼 | 오타 | 기본 글자 크기  |
|-----------------:|:-------------:|:-----------:|:---:|:-------------:|
|  true_final.docx |       -       |      -      | YES |     10 pt     |
|  real_final.docx |       -       |      -      |  -  |      9 pt     |
| final_final.docx | bio-photo.jpg |      -      | YES |     10 pt     |
|   index (1).html |       -       |      -      | YES |     10 pt     |
|       index.html |       -       |     YES     |  -  |      9 pt     |

: Before Solution

:::

사진이나 다운로드 버튼을 추가하고 싶으면 반드시 어느 파일 하나에 다른 정보와 함께 저장해야 하는 삽입 이상이 있어요.

그리고 실수로 그 파일을 삭제하면 기껏 추가한 사진이나 다운로드 버튼까지 덩달아 없어지는 삭제 이상이 있어요.
필요하면 시간을 들여 다시 만들어야 해요.

또한 이미 제출한 MS Word 파일을 고치기 위해 사본을 만들거나 웹페이지에 옮기면 중복 데이터가 생기는 셈이에요.
그러므로 고치려면 마지막으로 고친 파일만 순차적(Serializable)으로 고치거나 모든 파일들을 원자적(Atomic)으로 한꺼번에 고쳐야 해요.
그러나 실수로 다른 파일을 고쳐서 정작 고쳐야 할 최신 파일 또는 모든 파일을 고친다는 보장이 없는 갱신 이상이 있어요.
그래서 마지막으로 고친 파일의 오타나 기본 글자 크기가 정말 최신인지 아니면 실수로 번복한 것인지 헷갈려요.

:::{.column-page-inset}

|       파일명      | bio-photo.jpg | 다운로드 버튼 | 오타 | 기본 글자 크기-10-pt | 기본 글자 크기-9-pt | 주석 |
|-----------------:|:-------------:|:-----------:|-----|:------------------:|:-----------------:|:---:|
|  index.qmd&ensp; |      YES      |     YES     | YES |        YES         |        YES        | YES |
|       final.docx |      YES      |      -      | YES |        YES         |         -         |  -  |
|       index.html |       -       |     YES     | YES |         -          |        YES        |  -  |

: After Solution

:::

이러한 이상 현상(Anomaly)들은 `index.qmd`라는 소스코드 하나를 관리하고 다른 파일로 변환함으로써 해결할 수 있어요.

추가할 것은 소스코드에 주석처럼 추가함으로써 다른 어느 파일로도 배포하지 않을 수 있어요.

삭제할 것은 소스코드에서 주석처럼 처리함으로써 아예 없어져서 복구가 안 되는 상황을 막을 수 있어요.

고칠 것은 소스코드가 선점(Preemptive)하기 때문에 소스코드를 변환한 MS Word 파일이나 웹페이지 둘 다 오타가 중복된다면 한꺼번에 원자적으로(Atomic) 확인하고 고치게 된다는 보장이 생겨요.

오타와는 반대로 기본 글자 크기는 통일하지 않는 것이 갱신 이상 현상(Anomaly)이 아니라 오히려 정상일 수 있어요.
그래서 같은 칼럼의 서로 다른 값인 10 pt와 9 pt를 각각 서로 다른 칼럼으로 나눔으로써 각각 선택할 수 있게 했습니다.
물론 한 파일이 10 pt와 9 pt를 동시에 포함할 필요는 없으니 괜히 그러지 않도록 확인하면 좋습니다.

한 파일이 어떤 칼럼을 포함할지 또는 포함하지 않을지는 파일마다 목록을 저장해서 관리할 수 있어요.
하지만 반대로 칼럼마다 어느 파일에 포함될지 또는 포함하지 않을지를 저장하는 방법도 있어요 [@king_dropbox_sharelist].
후자가 [Quarto](Conditional Content https://quarto.org/docs/authoring/conditional.html)에서 사용하는 방법이에요.

다만 Quarto는 소스코드를 변환할 파일마다 전체 칼럼을 탐색하는 것이 칼럼마다 해당하는 파일을 탐색하는 ElasticSearch의 Inverted Index와의 차이점이에요 [see @king_ticketmaster_search].
한편 칼럼마다 해당하는 파일을 탐색하는 기능은 모노레포의 소스코드를 다양한 방식으로 조합해서 배포할 수 있게 지원하는 Polylith에서도 지원하는 기능이에요.
Python Polylith도 이러한 [deps](https://davidvujic.blogspot.com/2024/02/python-monorepo-visualization.html) 기능을 지원하고, 위 표와 같은 Matrix도 확인할 수 있어요.

# Future Work

최종 문서를 각각 편집하지 않고 크로스 플랫폼 소스코드를 텍스트로 관리하기 시작하면 LLM 활용도 더 잘할 수 있을 거예요.