---
title: "Philemon 1:1-12"
author: "Yunho Kee"
date: "2024-02-14"
categories: [bible, Philemon, Paul, Timothy, Apphia, Archippus, Onesimus]
---

a prisoner for preaching  
a prisoner for the sake of

God our Father  
Christ Jesus  
the Lord Jesus Christ  
the Lord Jesus  
Christ

our brother  
our beloved co-worker  
our sister  
our fellow soldier  
all of God's people  
my child  
his father in the faith

give you grace and peace

집에서 모이는 교회도 있다.

thanksgiving and prayer  
love for

사람을 위해 기도한다.  
사람이 하나님을 믿고 하나님의 사람들을 사랑한다면 하나님께 감사할 일이다.  
그런데 하나님의 사람은 누구일까?

믿는 사람은 이해하고 경험하면서 너그러워진다.  
너그러움이 행동까지 이어지도록 기도한다.

refresh the hearts of God's people

친절은 마음을 회복시킨다.  
회복은 기분 좋은 일이다.

ask a favor of you  
do a favor for me  
demand the right thing in the name of Christ  
prefer simply to ask you  
appeal for  
appeal to you to show kindness to my child  

while here in prison  
hasn't been of much use to you in the past  
now he is very useful to both of us

# References
1. New Living Translation. (2015). Tyndale. https://www.tyndale.com/nlt/search
