service: aws-python-project
frameworkVersion: '3'
package:
  artifact: dist/example_my_aws_lambda_project-1.1.1-py3-none-any.whl

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-north-1

functions:
  hello:
    handler: yhkee0404.example_greet_aws_lambda.core.handler

plugins:
  - serverless-python-requirements
